//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Transfer = new HashSet<Transfer>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> SubdivID { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Subdivision Subdivision { get; set; }
        public virtual ICollection<Transfer> Transfer { get; set; }
    }
}
