//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int ID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> FinRespPerson { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
